### ISSUE TITLE
ValueError:"Can't load save_path when it is None."

### ISSUE THREAD

**Issue by wnzhyee** [balancap/SSD-Tensorflow#156]
I run this shell in terminal:
```
#!/bin/bash
DATASET_DIR=/home/waka/data/VOCdevkit/VOC2007_tfrecord/
TRAIN_DIR=./log_files/log_train/
CHECKPOINT_PATH=./checkpoints/ssd_300_vgg.ckpt
python3 ./train_ssd_network.py \
    --train_dir=${TRAIN_DIR} \
    --dataset_dir=${DATASET_DIR} \
    --dataset_name=pascalvoc_2007 \
    --dataset_split_name=train \
    --model_name=ssd_300_vgg \
    --checkpoint_path=${CHECKPOINT_PATH} \
    --save_summaries_secs=60 \
    --save_interval_secs=600 \
    --weight_decay=0.0005 \
    --optimizer=adam \
    --learning_rate=0.001 \
    --batch_size=32
```
and i meet this problem:

```
# =========================================================================== #
# Training | Evaluation flags:
# =========================================================================== #
{'adadelta_rho': 0.95,
 'adagrad_initial_accumulator_value': 0.1,
 'adam_beta1': 0.9,
 'adam_beta2': 0.999,
 'batch_size': 32,
 'checkpoint_exclude_scopes': None,
 'checkpoint_model_scope': None,
 'checkpoint_path': './checkpoints/ssd_300_vgg.ckpt',
 'clone_on_cpu': False,
 'dataset_dir': '/home/waka/data/VOCdevkit/VOC2007_tfrecord/',
 'dataset_name': 'pascalvoc_2007',
 'dataset_split_name': 'train',
 'end_learning_rate': 0.0001,
 'ftrl_initial_accumulator_value': 0.1,
 'ftrl_l1': 0.0,
 'ftrl_l2': 0.0,
 'ftrl_learning_rate_power': -0.5,
 'gpu_memory_fraction': 0.8,
 'ignore_missing_vars': False,
 'label_smoothing': 0.0,
 'labels_offset': 0,
 'learning_rate': 0.001,
 'learning_rate_decay_factor': 0.94,
 'learning_rate_decay_type': 'exponential',
 'log_every_n_steps': 10,
 'loss_alpha': 1.0,
 'match_threshold': 0.5,
 'max_number_of_steps': None,
 'model_name': 'ssd_300_vgg',
 'momentum': 0.9,
 'moving_average_decay': None,
 'negative_ratio': 3.0,
 'num_classes': 21,
 'num_clones': 1,
 'num_epochs_per_decay': 2.0,
 'num_preprocessing_threads': 4,
 'num_readers': 4,
 'opt_epsilon': 1.0,
 'optimizer': 'adam',
 'preprocessing_name': None,
 'rmsprop_decay': 0.9,
 'rmsprop_momentum': 0.9,
 'save_interval_secs': 600,
 'save_summaries_secs': 60,
 'train_dir': './log_files/log_train/',
 'train_image_size': None,
 'trainable_scopes': None,
 'weight_decay': 0.0005}

# =========================================================================== #
# SSD net parameters:
# =========================================================================== #
{'anchor_offset': 0.5,
 'anchor_ratios': [[2, 0.5],
                   [2, 0.5, 3, 0.3333333333333333],
                   [2, 0.5, 3, 0.3333333333333333],
                   [2, 0.5, 3, 0.3333333333333333],
                   [2, 0.5],
                   [2, 0.5]],
 'anchor_size_bounds': [0.15, 0.9],
 'anchor_sizes': [(21.0, 45.0),
                  (45.0, 99.0),
                  (99.0, 153.0),
                  (153.0, 207.0),
                  (207.0, 261.0),
                  (261.0, 315.0)],
 'anchor_steps': [8, 16, 32, 64, 100, 300],
 'feat_layers': ['block4', 'block7', 'block8', 'block9', 'block10', 'block11'],
 'feat_shapes': [(38, 38), (19, 19), (10, 10), (5, 5), (3, 3), (1, 1)],
 'img_shape': (300, 300),
 'no_annotation_label': 21,
 'normalizations': [20, -1, -1, -1, -1, -1],
 'num_classes': 21,
 'prior_scaling': [0.1, 0.1, 0.2, 0.2]}

# =========================================================================== #
# Training | Evaluation dataset files:
# =========================================================================== #
['/home/waka/data/VOCdevkit/VOC2007_tfrecord/voc_2007_train_000.tfrecord',
 '/home/waka/data/VOCdevkit/VOC2007_tfrecord/voc_2007_train_001.tfrecord',
 '/home/waka/data/VOCdevkit/VOC2007_tfrecord/voc_2007_train_002.tfrecord',
 '/home/waka/data/VOCdevkit/VOC2007_tfrecord/voc_2007_train_003.tfrecord',
 '/home/waka/data/VOCdevkit/VOC2007_tfrecord/voc_2007_train_004.tfrecord',
 '/home/waka/data/VOCdevkit/VOC2007_tfrecord/voc_2007_train_005.tfrecord',
 '/home/waka/data/VOCdevkit/VOC2007_tfrecord/voc_2007_train_006.tfrecord',
 '/home/waka/data/VOCdevkit/VOC2007_tfrecord/voc_2007_train_007.tfrecord',
 '/home/waka/data/VOCdevkit/VOC2007_tfrecord/voc_2007_train_008.tfrecord',
 '/home/waka/data/VOCdevkit/VOC2007_tfrecord/voc_2007_train_009.tfrecord',
 '/home/waka/data/VOCdevkit/VOC2007_tfrecord/voc_2007_train_010.tfrecord',
 '/home/waka/data/VOCdevkit/VOC2007_tfrecord/voc_2007_train_011.tfrecord',
 '/home/waka/data/VOCdevkit/VOC2007_tfrecord/voc_2007_train_012.tfrecord',
 '/home/waka/data/VOCdevkit/VOC2007_tfrecord/voc_2007_train_013.tfrecord',
 '/home/waka/data/VOCdevkit/VOC2007_tfrecord/voc_2007_train_014.tfrecord',
 '/home/waka/data/VOCdevkit/VOC2007_tfrecord/voc_2007_train_015.tfrecord',
 '/home/waka/data/VOCdevkit/VOC2007_tfrecord/voc_2007_train_016.tfrecord',
 '/home/waka/data/VOCdevkit/VOC2007_tfrecord/voc_2007_train_017.tfrecord',
 '/home/waka/data/VOCdevkit/VOC2007_tfrecord/voc_2007_train_018.tfrecord',
 '/home/waka/data/VOCdevkit/VOC2007_tfrecord/voc_2007_train_019.tfrecord',
 '/home/waka/data/VOCdevkit/VOC2007_tfrecord/voc_2007_train_020.tfrecord',
 '/home/waka/data/VOCdevkit/VOC2007_tfrecord/voc_2007_train_021.tfrecord',
 '/home/waka/data/VOCdevkit/VOC2007_tfrecord/voc_2007_train_022.tfrecord',
 '/home/waka/data/VOCdevkit/VOC2007_tfrecord/voc_2007_train_023.tfrecord',
 '/home/waka/data/VOCdevkit/VOC2007_tfrecord/voc_2007_train_024.tfrecord',
 '/home/waka/data/VOCdevkit/VOC2007_tfrecord/voc_2007_train_025.tfrecord',
 '/home/waka/data/VOCdevkit/VOC2007_tfrecord/voc_2007_train_026.tfrecord',
 '/home/waka/data/VOCdevkit/VOC2007_tfrecord/voc_2007_train_027.tfrecord',
 '/home/waka/data/VOCdevkit/VOC2007_tfrecord/voc_2007_train_028.tfrecord',
 '/home/waka/data/VOCdevkit/VOC2007_tfrecord/voc_2007_train_029.tfrecord',
 '/home/waka/data/VOCdevkit/VOC2007_tfrecord/voc_2007_train_030.tfrecord',
 '/home/waka/data/VOCdevkit/VOC2007_tfrecord/voc_2007_train_031.tfrecord',
 '/home/waka/data/VOCdevkit/VOC2007_tfrecord/voc_2007_train_032.tfrecord',
 '/home/waka/data/VOCdevkit/VOC2007_tfrecord/voc_2007_train_033.tfrecord',
 '/home/waka/data/VOCdevkit/VOC2007_tfrecord/voc_2007_train_034.tfrecord',
 '/home/waka/data/VOCdevkit/VOC2007_tfrecord/voc_2007_train_035.tfrecord',
 '/home/waka/data/VOCdevkit/VOC2007_tfrecord/voc_2007_train_036.tfrecord',
 '/home/waka/data/VOCdevkit/VOC2007_tfrecord/voc_2007_train_037.tfrecord',
 '/home/waka/data/VOCdevkit/VOC2007_tfrecord/voc_2007_train_038.tfrecord',
 '/home/waka/data/VOCdevkit/VOC2007_tfrecord/voc_2007_train_039.tfrecord',
 '/home/waka/data/VOCdevkit/VOC2007_tfrecord/voc_2007_train_040.tfrecord',
 '/home/waka/data/VOCdevkit/VOC2007_tfrecord/voc_2007_train_041.tfrecord',
 '/home/waka/data/VOCdevkit/VOC2007_tfrecord/voc_2007_train_042.tfrecord',
 '/home/waka/data/VOCdevkit/VOC2007_tfrecord/voc_2007_train_043.tfrecord',
 '/home/waka/data/VOCdevkit/VOC2007_tfrecord/voc_2007_train_044.tfrecord',
 '/home/waka/data/VOCdevkit/VOC2007_tfrecord/voc_2007_train_045.tfrecord',
 '/home/waka/data/VOCdevkit/VOC2007_tfrecord/voc_2007_train_046.tfrecord',
 '/home/waka/data/VOCdevkit/VOC2007_tfrecord/voc_2007_train_047.tfrecord',
 '/home/waka/data/VOCdevkit/VOC2007_tfrecord/voc_2007_train_048.tfrecord',
 '/home/waka/data/VOCdevkit/VOC2007_tfrecord/voc_2007_train_049.tfrecord']

INFO:tensorflow:Fine-tuning from None. Ignoring missing vars: False
2017-10-28 23:23:53.896333: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-10-28 23:23:53.896356: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-10-28 23:23:53.896360: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-10-28 23:23:53.896363: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-10-28 23:23:53.896366: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
2017-10-28 23:23:54.033333: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:893] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2017-10-28 23:23:54.033666: I tensorflow/core/common_runtime/gpu/gpu_device.cc:955] Found device 0 with properties: 
name: GeForce GTX 1080 Ti
major: 6 minor: 1 memoryClockRate (GHz) 1.582
pciBusID 0000:03:00.0
Total memory: 10.91GiB
Free memory: 10.55GiB
2017-10-28 23:23:54.033678: I tensorflow/core/common_runtime/gpu/gpu_device.cc:976] DMA: 0 
2017-10-28 23:23:54.033681: I tensorflow/core/common_runtime/gpu/gpu_device.cc:986] 0:   Y 
2017-10-28 23:23:54.033686: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1045] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:03:00.0)
INFO:tensorflow:Error reported to Coordinator: <class 'ValueError'>, Can't load save_path when it is None.
Traceback (most recent call last):
  File "./train_ssd_network.py", line 377, in <module>
    tf.app.run()
  File "/home/waka/yangwz/py3env/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "./train_ssd_network.py", line 373, in main
    slim.learning.train(train_tensor,logdir=FLAGS.train_dir,master='',is_chief=True,init_fn=tf_utils.get_init_fn(FLAGS),summary_op=summary_op,number_of_steps=FLAGS.max_number_of_steps,log_every_n_steps=FLAGS.log_every_n_steps,save_summaries_secs=FLAGS.save_summaries_secs,saver=saver,save_interval_secs=FLAGS.save_interval_secs,session_config=config,sync_optimizer=None)
  File "/home/waka/yangwz/py3env/lib/python3.5/site-packages/tensorflow/contrib/slim/python/slim/learning.py", line 738, in train
    master, start_standard_services=False, config=session_config) as sess:
  File "/usr/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/home/waka/yangwz/py3env/lib/python3.5/site-packages/tensorflow/python/training/supervisor.py", line 964, in managed_session
    self.stop(close_summary_writer=close_summary_writer)
  File "/home/waka/yangwz/py3env/lib/python3.5/site-packages/tensorflow/python/training/supervisor.py", line 792, in stop
    stop_grace_period_secs=self._stop_grace_secs)
  File "/home/waka/yangwz/py3env/lib/python3.5/site-packages/tensorflow/python/training/coordinator.py", line 389, in join
    six.reraise(*self._exc_info_to_raise)
  File "/home/waka/yangwz/py3env/lib/python3.5/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/waka/yangwz/py3env/lib/python3.5/site-packages/tensorflow/python/training/supervisor.py", line 953, in managed_session
    start_standard_services=start_standard_services)
  File "/home/waka/yangwz/py3env/lib/python3.5/site-packages/tensorflow/python/training/supervisor.py", line 708, in prepare_or_wait_for_session
    init_feed_dict=self._init_feed_dict, init_fn=self._init_fn)
  File "/home/waka/yangwz/py3env/lib/python3.5/site-packages/tensorflow/python/training/session_manager.py", line 281, in prepare_session
    init_fn(sess)
  File "/home/waka/yangwz/py3env/lib/python3.5/site-packages/tensorflow/contrib/framework/python/ops/variables.py", line 660, in callback
    saver.restore(session, model_path)
  File "/home/waka/yangwz/py3env/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1557, in restore
    raise ValueError("Can't load save_path when it is None.")
ValueError: Can't load save_path when it is None.
ERROR:tensorflow:==================================
Object was never used (type <class 'tensorflow.python.framework.ops.Tensor'>):
<tf.Tensor 'init_ops/report_uninitialized_variables/boolean_mask/Gather:0' shape=(?,) dtype=string>
If you want to mark it as used call its "mark_used()" method.
It was originally created here:
['File "./train_ssd_network.py", line 377, in <module>\n    tf.app.run()', 'File "/home/waka/yangwz/py3env/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 48, in run\n    _sys.exit(main(_sys.argv[:1] + flags_passthrough))', 'File "./train_ssd_network.py", line 373, in main\n    slim.learning.train(train_tensor,logdir=FLAGS.train_dir,master=\'\',is_chief=True,init_fn=tf_utils.get_init_fn(FLAGS),summary_op=summary_op,number_of_steps=FLAGS.max_number_of_steps,log_every_n_steps=FLAGS.log_every_n_steps,save_summaries_secs=FLAGS.save_summaries_secs,saver=saver,save_interval_secs=FLAGS.save_interval_secs,session_config=config,sync_optimizer=None)', 'File "/home/waka/yangwz/py3env/lib/python3.5/site-packages/tensorflow/contrib/slim/python/slim/learning.py", line 663, in train\n    ready_op = tf_variables.report_uninitialized_variables()', 'File "/home/waka/yangwz/py3env/lib/python3.5/site-packages/tensorflow/python/util/tf_should_use.py", line 175, in wrapped\n    return _add_should_use_warning(fn(*args, **kwargs))', 'File "/home/waka/yangwz/py3env/lib/python3.5/site-packages/tensorflow/python/util/tf_should_use.py", line 144, in _add_should_use_warning\n    wrapped = TFShouldUseWarningWrapper(x)', 'File "/home/waka/yangwz/py3env/lib/python3.5/site-packages/tensorflow/python/util/tf_should_use.py", line 101, in __init__\n    stack = [s.strip() for s in traceback.format_stack()]']
==================================

```

I wonder what's wrong in it?

**Comment by xiaoluojun** [comment]
I need help too!

**Comment by 3born** [comment]
`INFO:tensorflow:Fine-tuning from None. Ignoring missing vars: False`
It seems as though your checkpoint isn't found properly. I reproduced the same error when I omitted the checkpoint path, i.e. `--checkpoint_path= ` and when the variable CHECKPOINT_PATH was unspecified. It's pretty weird, because you assign it prior to the function call. Try passing the path directly, i.e. `--checkpoint_path=/path/to/checkpoint.ckpt`.

**Comment by bryantChhun** [comment]
Check the way the flags are defined in your "train_ssd_network.py". 

I found a parallel case with export_inference_graph.py, which had checkpoint flag changed to "trained_checkpoint_prefix" in the newest version of object_detection.

The eval flags reported suggest this isn't the problem, but i figured I'd throw out the idea.

**Comment by xiaoluojun** [comment]
通过各种尝试，这是模型路劲的错误。

**Comment by honest2017** [comment]
怎么解决

**Comment by mfp305629415** [comment]
friend，how  to do

**Comment by ruhutianyi** [comment]
I encountered the same problem, how to solve it please

**Comment by mahyaar** [comment]
Make sure that the "checkpoint" file is included in your checkpoint directory

**Comment by gautamMalu** [comment]
@wnzhyee check the  'checkpoint_model_scope': None,
Flag and set it to ssd_vgg_300

**Comment by Eden2017** [comment]
I got the same error, how to change the correct path？ @xiaoluojun

**Comment by ruhutianyi** [comment]
My problem is solved, try to fill in the relative path, like this：
CHECKPOINT_PATH=checkpoints/ssd_300_vgg.ckpt
Then open the terminal in the corresponding directory, enter directly：
python3 train_ssd_network.py

**Comment by ClaireTun** [comment]
I tried the ways mentioned above,but still have the problem?  Any ideas?

**Comment by TingZhang08** [comment]
I encountered the same problem, could anyone give us some ideas?

**Comment by callmeray** [comment]
The reason is you've unzip it into a subfolder, so the path should be:
CHECKPOINT_PATH='./checkpoints/ssd_300_vgg.ckpt/ssd_300_vgg.ckpt'

**Comment by tf71991** [comment]
I'm also receiving the same error when trying to use a pre-trained model. I have tried the recommended solutions above, but they didn't work. Would be great if someone can help, thx

**Comment by ccyyy** [comment]
我的路径是正确的，检查了很多次了，可是还是会报这个错误，实在不知道是什么原因了 @xiaoluojun

**Comment by ccyyy** [comment]
Have you got any good solutions to the problem? @tf71991

**Comment by Just-A-Peek** [comment]
@wnzhyee Have you solve the problem?

**Comment by ccyyy** [comment]
For example, the checkpoint path must be CHECKPOINT_PATH='./checkpoints/ssd_300_vgg.ckpt/ssd_300_vgg.ckpt', you need to input two times the file of .ckpt.

**Comment by APPZu** [comment]
But my checkpoint folder doesn't have .ckpt file how should I do? There is only DESKTOP-FH9K1FE file and pbtxt file. I don't know what they are?

**Comment by ghost** [comment]
I have already solved the problem :
1:check 'train_ssd_network.py' line 135 'num_classes' is correct?
2.--checkpoint_path=checkpoints/ssd_300_vgg.ckpt ------>
--CHECKPOINT_PATH=checkpoints/ssd_300_vgg.ckpt  You should change it in capital.

**Comment by RanFeng** [comment]
> The reason is you've unzip it into a subfolder, so the path should be:
> CHECKPOINT_PATH='./checkpoints/ssd_300_vgg.ckpt/ssd_300_vgg.ckpt'

Thanks , That's a lot help!

**Comment by Holmeyoung** [comment]
> I have already solved the problem :
> 1:check 'train_ssd_network.py' line 135 'num_classes' is correct?
> 2.--checkpoint_path=checkpoints/ssd_300_vgg.ckpt ------>
> --CHECKPOINT_PATH=checkpoints/ssd_300_vgg.ckpt You should change it in capital.

Thanks a lot. It's the right solution for me!

**Comment by Wenqiang-Miao** [comment]
> I have already solved the problem :
> 1:check 'train_ssd_network.py' line 135 'num_classes' is correct?
> 2.--checkpoint_path=checkpoints/ssd_300_vgg.ckpt ------>
> --CHECKPOINT_PATH=checkpoints/ssd_300_vgg.ckpt You should change it in capital.

Thank you a lot.

**Comment by cjnjuwhy** [comment]
根据前面人的提示，在代码中注释掉关于checkpoint就可以运行了。
```
DATASET_DIR=/Users/huanyu_wang/Public/Git-Files/SSD-Tensorflow/tfrecords
TRAIN_DIR=./logs/ssd_300_vgg_3
#CHECKPOINT_PATH=./checkpoints/ssd_300_vgg.ckpt
python train_ssd_network.py \
    --train_dir=${TRAIN_DIR} \
    --dataset_dir=${DATASET_DIR} \
    --dataset_name=pascalvoc_2007 \
    --dataset_split_name=train \
    --model_name=ssd_300_vgg \
    #--checkpoint_path=${CHECKPOINT_PATH} \
    --save_summaries_secs=60 \
    --save_interval_secs=600 \
    --weight_decay=0.0005 \
    --optimizer=adam \
    --learning_rate=0.001 \
    --learning_rate_decay_factor=0.95 \
    --batch_size=32
```

**Comment by cjnjuwhy** [comment]
> 根据前面人的提示，在代码中注释掉关于checkpoint就可以运行了。
> 
> ```
> DATASET_DIR=/Users/huanyu_wang/Public/Git-Files/SSD-Tensorflow/tfrecords
> TRAIN_DIR=./logs/ssd_300_vgg_3
> #CHECKPOINT_PATH=./checkpoints/ssd_300_vgg.ckpt
> python train_ssd_network.py \
>     --train_dir=${TRAIN_DIR} \
>     --dataset_dir=${DATASET_DIR} \
>     --dataset_name=pascalvoc_2007 \
>     --dataset_split_name=train \
>     --model_name=ssd_300_vgg \
>     #--checkpoint_path=${CHECKPOINT_PATH} \
>     --save_summaries_secs=60 \
>     --save_interval_secs=600 \
>     --weight_decay=0.0005 \
>     --optimizer=adam \
>     --learning_rate=0.001 \
>     --learning_rate_decay_factor=0.95 \
>     --batch_size=32
> ```

如果想fin-tune的话，需要将`CHECKPOINT_PATH`指定到文件而不是文件夹，例如`./checkpoints/ssd_300_vgg.ckpt/ssd_300_vgg.ckpt`,因为官方给定的文件也是`.ckpt`后缀。

You should assign `CHECKPOINT_PATH` rather than `CHECKPOINT_DIR`, the filename and the dir_name its the same, that is the point.

**Comment by cpoptic** [comment]
> Make sure that the "checkpoint" file is included in your checkpoint directory

Yep this solved it for me.  Can't believe how many hours spent tracking down this.  The TF documentation is 1) scattered, 2) inconsistent, and 3) incomplete   on many issues like this.  Little details that if you do not get correct will simply cause model restoring to fail.

For this specific issue, you need 4 files in your checkpoint directory, not 3 (at least for me on TF 1.14).
For example:

1. model.ckpt-200000.index
2. model.ckpt-200000.data-00000-of-00001
3. model.ckpt-200000.meta
4.  checkpoint  file  *** This 4th one was the missing link. ***  It's just a simple text file containing a list of all checkpoints trained and saved on the model.   For example:

> model_checkpoint_path: "model.ckpt-200000"
> all_model_checkpoint_paths: "model.ckpt-195190"
> all_model_checkpoint_paths: "model.ckpt-196406"
> all_model_checkpoint_paths: "model.ckpt-197625"
> all_model_checkpoint_paths: "model.ckpt-198847"
> all_model_checkpoint_paths: "model.ckpt-200000"

**Comment by yuqli** [comment]
@cpoptic Thanks for pointing this out. This is exactly my mistake too. TF documentation sucks.

**Comment by qipengh** [comment]
介绍一下我的解决方案

> > 根据前面人的提示，在代码中注释掉关于checkpoint就可以运行了。
> > ```
> > DATASET_DIR=/Users/huanyu_wang/Public/Git-Files/SSD-Tensorflow/tfrecords
> > TRAIN_DIR=./logs/ssd_300_vgg_3
> > #CHECKPOINT_PATH=./checkpoints/ssd_300_vgg.ckpt
> > python train_ssd_network.py \
> >     --train_dir=${TRAIN_DIR} \
> >     --dataset_dir=${DATASET_DIR} \
> >     --dataset_name=pascalvoc_2007 \
> >     --dataset_split_name=train \
> >     --model_name=ssd_300_vgg \
> >     #--checkpoint_path=${CHECKPOINT_PATH} \
> >     --save_summaries_secs=60 \
> >     --save_interval_secs=600 \
> >     --weight_decay=0.0005 \
> >     --optimizer=adam \
> >     --learning_rate=0.001 \
> >     --learning_rate_decay_factor=0.95 \
> >     --batch_size=32
> > ```
> 
> 如果想fin-tune的话，需要将`CHECKPOINT_PATH`指定到文件而不是文件夹，例如`./checkpoints/ssd_300_vgg.ckpt/ssd_300_vgg.ckpt`,因为官方给定的文件也是`.ckpt`后缀。
> 
> You should assign `CHECKPOINT_PATH` rather than `CHECKPOINT_DIR`, the filename and the dir_name its the same, that is the point.

--------分割线---------
介绍一下我的问题和解决办法
问题1：ValueError: Can't load save_path when it is None.
解决1：由于我的ckpt目录是./ckpt/，具体文件是model.ckpt-823199.xxxxxxx。于是我设置了--checkpoint_path="./ckpt_inv1/model.ckpt"。接下来就有了问题2的报错信息；
问题2：ValueError: The passed save_path is not a valid checkpoint: ./ckpt_inv1/model.ckpt
解决2：由于我是finetune(1000 step)，所以指定--checkpoint_path="./ckpt_inv1/model.ckpt-823199"，就能正常训练了。

希望能帮到大家，尽量具体到实际的ckpt(也就是.xxx之前的部分)

**Comment by iFactory3D** [comment]
> I have already solved the problem : 1:check 'train_ssd_network.py' line 135 'num_classes' is correct? 2.--checkpoint_path=checkpoints/ssd_300_vgg.ckpt ------> --CHECKPOINT_PATH=checkpoints/ssd_300_vgg.ckpt You should change it in capital.

This worked. thanks a lot.

**Comment by Muhibullah1** [comment]
> `INFO:tensorflow:Fine-tuning from None. Ignoring missing vars: False` It seems as though your checkpoint isn't found properly. I reproduced the same error when I omitted the checkpoint path, i.e. `--checkpoint_path= ` and when the variable CHECKPOINT_PATH was unspecified. It's pretty weird, because you assign it prior to the function call. Try passing the path directly, i.e. `--checkpoint_path=/path/to/checkpoint.ckpt`.

this worked for me, thanks

**Comment by hupf80** [comment]
I'm still stuggeling with these issue.
I now tried to set the checkpoint-path in each place i know:
At the call of the `train_ssd_network.py´ I added:  `--checkpoint_path=...`
Also in the `train_ssd_network.py´ I set the `CHECKPOINT_PATH`to the absolute path of the *index and the *data-00000-of-00001

Does any of you know how to fix this?

@cpoptic What does it mean, i need four files? Where can I get the other two files? Do I have to generate those? In the Repo under "checkpoints", when I unzip the chpk.zip, there are only the index and the data-00000-of-00001 - files...


Thanks a Lot!!
